# Generated by Django 5.2.17 on 2026-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Dr. Jansi's Dermverse", max_length=150),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="Skin, Hair & Laser Clinic", max_length=150
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "address",
                    models.TextField(
                        default="11/10, Jayaram Avenue, Shastri Nagar, Adyar, Chennai - 600 090"
                    ),
                ),
                ("state", models.CharField(default="Tamil Nadu", max_length=60)),
                ("phone", models.CharField(default="73580 72111", max_length=60)),
                ("whatsapp", models.CharField(default="91765 67011", max_length=60)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="dermverseclinic@gmail.com", max_length=254
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=200)),
                (
                    "google_business",
                    models.CharField(
                        blank=True, default="Dr Jansi's Dermverse", max_length=200
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="Mon – Sat, 10:00 AM – 8:00 PM",
                        max_length=120,
                    ),
                ),
                (
                    "gstin",
                    models.CharField(blank=True, max_length=20, verbose_name="GSTIN"),
                ),
                (
                    "registration_no",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Clinic registration / licence no.",
                    ),
                ),
                ("invoice_prefix", models.CharField(default="DV", max_length=10)),
                (
                    "round_off_total",
                    models.BooleanField(
                        default=True,
                        help_text="Round invoice totals to the nearest rupee",
                    ),
                ),
                ("show_doctor_registration", models.BooleanField(default=False)),
                (
                    "invoice_terms",
                    models.TextField(
                        blank=True,
                        default="This is a computer-generated invoice.\nPackages and sessions are non-transferable.",
                    ),
                ),
                ("refund_policy", models.TextField(blank=True)),
                (
                    "invoice_footer",
                    models.CharField(
                        blank=True,
                        default="Thank you for choosing Dermverse.",
                        max_length=200,
                    ),
                ),
                ("signature", models.ImageField(blank=True, upload_to="clinic/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinic settings",
                "verbose_name_plural": "Clinic settings",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("qualification", models.CharField(blank=True, max_length=120)),
                ("registration_no", models.CharField(blank=True, max_length=60)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30)),
                ("year", models.PositiveIntegerField(default=0)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "year"), name="unique_sequence_per_year"
                    )
                ],
            },
        ),
    ]
